TTT-10 [RELEASE-0.1 ] refactoring CustomButton component
Musa-94/tic-tac-toe pull request #13
Opened 2021-03-28 06:18 UTC by zabrat

Сделано:
1) Добавил события в компоненту
2) Добавил Wrapper для кнопки

Проверять:
1) Попередавать разные события в компоненту и просмотреть их срабатывание

2021-03-28 13:03 UTC, zabrat commented
![](https://github.trello.services/images/mini-trello-icon.png) [написать тесты на language Manager](https://trello.com/c/mPGE4D4m/19-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%82%D0%B5%D1%81%D1%82%D1%8B-%D0%BD%D0%B0-language-manager)

2021-03-28 13:04 UTC, zabrat commented
![](https://github.trello.services/images/mini-trello-icon.png) [TTT-10 рефакторинг компоненты CustomButton](https://trello.com/c/PPdcqU1J/18-ttt-10-%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-custombutton)

2021-03-28 18:58 UTC, Musa-94 requested changes

2021-03-28 18:58 UTC, Musa-94 commented on src/components/customButton/CustomButton.tsx
> +                onClick={handleClick}
лесенка

2021-03-28 18:58 UTC, Musa-94 commented on src/modules/singUp/styledComponents.ts
> +
отностится к блоку Form, тут абзац не нужен

2021-03-28 18:58 UTC, Musa-94 commented on src/modules/singUp/styledComponents.ts
remove empty line

2021-03-28 18:58 UTC, Musa-94 commented on src/modules/singUp/styledComponents.ts
> +Form.ButtonWrapper = styled.div`
`Form.ButtonWrapper = styled.div``; `

2021-04-10 20:04 UTC, Musa-94 commented on src/modules/signUp/SignUp.tsx
> +                    <Form.ButtonWrapper>
мы договорились писать без миксинов, т.е. не нужно создавать такие компоненты Form.ButtonWrapper - делай сразу buttonWrapper

2021-04-10 20:04 UTC, Musa-94 commented on src/modules/signUp/styledComponents.ts
>  interface IContent extends StyledComponentBase<any, any> {
избавься от данных интерфейсов и не создавай миксины, интерфейсы пиши только для пропсов которые принимает компонента

2021-04-22 19:16 UTC, Musa-94 approved these changes

2021-04-22 19:16 UTC, merged