TTT-11 [RELEASE-0.1] covered language manager with testst
Musa-94/tic-tac-toe pull request #14
Opened 2021-03-28 12:58 UTC by zabrat

Сделано:
1) Покрыл тестами language manager (покрытие на 100%)

Проверять:
1) Процент покрытия

2021-03-28 13:04 UTC, zabrat commented
![](https://github.trello.services/images/mini-trello-icon.png) [написать тесты на language Manager](https://trello.com/c/mPGE4D4m/19-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%82%D0%B5%D1%81%D1%82%D1%8B-%D0%BD%D0%B0-language-manager)

2021-03-28 18:53 UTC, Musa-94 requested changes

2021-03-28 18:53 UTC, Musa-94 commented on src/managers/languageManager/__tests__/reducer.test.ts
> +            payload: 'ru'
payload: 'ru' - лишнее, initialState тебе с английской локалю должен веруть язык

2021-03-28 18:53 UTC, Musa-94 commented on src/managers/languageManager/__tests__/reducer.test.ts
> +                type: 'change_language_store',
вынеси выше в переменную action

2021-03-28 18:53 UTC, Musa-94 commented on src/managers/languageManager/__tests__/saga.test.ts
> +        const action = {
табуляция съехала

2021-03-28 18:53 UTC, Musa-94 commented on src/managers/languageManager/__tests__/saga.test.ts
> +
remove empty line

2021-03-28 18:53 UTC, Musa-94 commented on src/managers/languageManager/__tests__/saga.test.ts
> +            // @ts-ignore
тут точно нужно это??? я думаю это лишнее

2021-03-28 18:53 UTC, Musa-94 commented on src/managers/languageManager/__tests__/saga.test.ts
> +            // @ts-ignore
тут точно нужно это??? я думаю в этом кейсе это лишнее

2021-03-28 18:53 UTC, Musa-94 commented on src/managers/languageManager/__tests__/reducer.test.ts
> +                type: 'change_language_store',
и запиши потом в 1 строчку

2021-04-06 10:54 UTC, zabrat commented on src/managers/languageManager/__tests__/saga.test.ts
> +            // @ts-ignore
ты про генератор или  тс игнор?

2021-04-10 19:58 UTC, Musa-94 commented on src/managers/languageManager/__tests__/saga.test.ts
> +            // @ts-ignore
ts-ignore

2021-04-11 20:21 UTC, Musa-94 commented on src/managers/languageManager/__tests__/reducer.test.ts
> +
remove empty line

2021-04-22 19:17 UTC, Musa-94 approved these changes

2021-04-22 19:18 UTC, merged